/**
 * Unit tests — report renderer (preview/PDF paper HTML).
 */
'use strict';

const h = require('./harness.js');
const { test, assert, assertEqual, FRG } = h;

function buildReport() {
    const registry = FRG.registry;
    registry.register(FRG.deviceStatusModule);

    const client = FRG.apiClient.create(h.mockApi);
    const controller = FRG.reportController.create({ client: client, registry: registry });

    return controller.generate(
        { groupIds: ['g-fleet'], groupNames: ['Fleet Operations'], reportDate: '2026-08-13', label: 'Fleet Operations' },
        ['device-status']
    );
}

test('renderPaper includes header metadata', function () {
    return buildReport().then(function (report) {
        const html = FRG.reportRenderer.renderPaper(report);

        assert(html.indexOf('Fleet Monitoring Report') >= 0, 'report name');
        assert(html.indexOf('Fleet Operations') >= 0, 'scope label');
        assert(html.indexOf('Current MyGeotab Database Context') >= 0, 'database label');
        assert(html.indexOf('Generated by') >= 0, 'footer present');
    });
});

test('renderPaper includes KPI numbers matching the module data', function () {
    return buildReport().then(function (report) {
        const data = report.sections[0].data;
        const html = FRG.reportRenderer.renderPaper(report);

        assert(html.indexOf('>' + data.statusCounts.total + '<') >= 0, 'total rendered');
        assert(html.indexOf('>' + data.statusCounts.online + '<') >= 0, 'online rendered');
        assert(html.indexOf('>' + data.statusCounts.offline + '<') >= 0, 'offline rendered');
    });
});

test('renderPaper shows module errors instead of fabricating numbers', function () {
    const failingApi = {
        call: function (method, params, cb, errCb) {
            errCb({ code: -32000, message: 'quota exceeded', data: { type: 'OverLimitException' } });
        },
        multiCall: function (calls, cb, errCb) {
            errCb('failed');
        },
        getSession: function () {}
    };

    const registry = FRG.registry;
    registry.register(FRG.deviceStatusModule);
    const client = FRG.apiClient.create(failingApi);
    const controller = FRG.reportController.create({ client: client, registry: registry });

    return controller.generate(
        { groupIds: [], groupNames: [], reportDate: null },
        ['device-status']
    ).then(function (report) {
        const html = FRG.reportRenderer.renderPaper(report);
        assert(html.indexOf('Module Errors') >= 0, 'error section present');
        assert(html.indexOf('larger than MyGeotab allows') >= 0, 'friendly OVER_LIMIT message');
        assert(html.indexOf('>0<') === -1, 'no fabricated zero values rendered');
    });
});
