/**
 * Report renderer — turns a normalized report model into the printable
 * preview/PDF HTML (the "report paper").
 *
 * The PDF output for the initial version is produced via the browser's native
 * print dialog (window.print), which applies the @media print styles in
 * addin.css. A dedicated PDF library remains a NEEDS VERIFICATION item.
 */
FRG.define('reportRenderer', function (FRG) {
    'use strict';

    function escapeHtml(value) {
        if (value === null || value === undefined) {
            return '';
        }
        return String(value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function renderMetadata(report) {
        var meta = report.metadata;

        return '<div class="report-head">' +
            '<div>' +
            '<div class="report-name">' + escapeHtml(meta.reportName) + '</div>' +
            '<div class="report-sub">' + escapeHtml(meta.scopeLabel || '') + '</div>' +
            '</div>' +
            '<div class="report-meta">' +
            'Database: ' + escapeHtml(meta.databaseLabel) + '<br>' +
            'Reporting Date: ' + escapeHtml(FRG.dateTime.formatDateOnly(meta.reportDate)) + '<br>' +
            'Generated: ' + escapeHtml(FRG.dateTime.formatLocal(meta.generatedAt)) +
            '</div>' +
            '</div>';
    }

    function renderFooter(report) {
        return '<div class="report-footer">' +
            '<span>Generated by ' + escapeHtml(FRG.PRODUCT) + '</span>' +
            '<span>Page 1</span>' +
            '</div>';
    }

    /**
     * Render the complete report paper HTML.
     *
     * @param {object} report - normalized report model from reportController.
     * @returns {string} HTML string.
     */
    function renderPaper(report) {
        var html = '<div class="report-paper">';
        html += renderMetadata(report);

        var okSections = report.sections.filter(function (section) {
            return section.status === 'ok';
        });

        var failedSections = report.sections.filter(function (section) {
            return section.status === 'error';
        });

        okSections.forEach(function (section) {
            var module = FRG.registry.get(section.moduleId);
            if (module && typeof module.renderSection === 'function') {
                html += module.renderSection(section.data);
            } else {
                html += '<div class="report-section-title">' + escapeHtml(section.title) + '</div>';
                html += '<p class="empty-note">Section data could not be rendered.</p>';
            }
        });

        if (okSections.length === 0) {
            html += '<p class="empty-note">No report modules produced data.</p>';
        }

        if (failedSections.length > 0) {
            html += '<div class="report-errors">';
            html += '<div class="report-section-title">Module Errors</div>';
            failedSections.forEach(function (section) {
                html += '<p>' + escapeHtml(section.title) + ': ' +
                    escapeHtml(FRG.errorHandler.userMessage(section.error)) + '</p>';
            });
            html += '</div>';
        }

        html += renderFooter(report);
        html += '</div>';
        return html;
    }

    return {
        renderPaper: renderPaper
    };
});
